[project]
name = "ai-agent"
version = "0.1.0"
description = "An AI agent with math tools and user data fetching."
authors = [{ name = "Rida Khan" }]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai-agents>=0.2.8",
    "python-decouple>=3.8",
]
